### ISSUE TITLE
error when sync blockchain at height 11626

### ISSUE THREAD

**Issue by ezioruan** [MovingCloudChain/mcc#1]
i just run the code in my local
here is the errors

![image](https://user-images.githubusercontent.com/631411/27481594-d9ca7e74-584f-11e7-8b46-b518e973547c.png)

seems that's an valid block
Block 42fb78c01f170d58a92454f032160f9425f3b68e30e8f589bfb565184f763b6e is not valid, ban 60 min 117.48.196.119:16833

**Comment by Stratocumulus88** [comment]
We are looking into this issue should get back to you today.

**Comment by MovingCloudChain** [comment]
We are still testing but you can try deleting the blockchain.db file then applying this patch and rebuilding.       
[a.patch.txt](https://github.com/xingyunmcc/mcc/files/1111242/a.patch.txt)

**Comment by MovingCloudChain** [comment]
Patch has been merged.   :-)
